In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [4]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\T460\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


0.9574074074074074

In [5]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.43703703703703706

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def get_score(model, X_train, X_test, y_traun, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [14]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

C:\Users\T460\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.8969359331476323

In [15]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold()

In [21]:
scores_logistic = []
scores_svm = []
scores_rf = []
for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [23]:
scores_logistic

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [24]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [25]:
scores_rf

[0.9348914858096828, 0.9565943238731218, 0.9181969949916527]

In [26]:
from sklearn.model_selection import cross_val_score

In [30]:
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target,cv=3)

array([0.91986644, 0.94156928, 0.91652755])

In [31]:
cross_val_score(SVC(), digits.data, digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92988314, 0.95993322, 0.92320534])